### ISSUE TITLE
Chiamate api e visualizzazione dei dati

### ISSUE THREAD

**Issue by LucaCarrero** [AugMantua/ScienceGround2021#7]
- [x] chiamate api per ottenere i terrari da mostrare (a9c03ed12cdb641ad0495075c94d32e1ddf9d25e)
- [x] chiamate api per ottenere i dati per popolare i grafici (eeb9a08865435a2cd88e92317914f5ada80e0602)
- [x] filtraggio dei dati dei grafici (periodo di tempo) (259d79d82280a495d48ff23b7bac0faa06bf3cbb)

**Comment by pmarchini** [comment]
Per i dati devo aggiornare le API, dobbiamo decidere come gestire le date

**Comment by pluisi** [comment]
Scegliete quello che fa più comodo

Pierluigi Luisi

Il ven 18 giu 2021, 22:30 Pietro Marchini ***@***.***> ha
scritto:

**Comment by LucaCarrero** [comment]
> Per i dati devo aggiornare le API, dobbiamo decidere come gestire le date 

Io a schermo lo mostro nel seguente modo: DD/MM/yyyy hh:mm

Dalle api mi piacerebbe riceverle nel seguente formato yyyyMMDDhhmm

Può andare?

**Comment by pluisi** [comment]
Per me ok

Pierluigi Luisi

Il sab 19 giu 2021, 13:18 Luca Carrero ***@***.***> ha
scritto:

**Comment by pmarchini** [comment]
Confermato yyyyMMDDhhmm con aggiunta secondi
